### ISSUE TITLE
Problem building app in iOS with PhonegapBuild.

### ISSUE THREAD

**Issue by shotoreaper** [Plotprojects/plot-phonegap-plugin#3]
When I build the app to iOS in Phonegapbuild, this returns this error:
Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture.

Now Apple force to build in 64-bit the applications.

**Comment by markvandertol** [comment]
This issue is specific to Phonegap build and isn't caused by the lack of support for arm64 by our plugin. There are two workarounds:

* Don't use Phonegap build and build your app locally.
* Use version 1.9.0 of our plugin. You can specify the plugin version in config.xml like so:
```<gap:plugin name="com.plotprojects.cordova" source="plugins.cordova.io" version="1.9.0" />```

We're looking into how to solve this issue.

**Comment by shotoreaper** [comment]
Ok, it build in PhonegapBuild perfectly if I use version 1.9.0. Thanks!

**Comment by markvandertol** [comment]
Building now works correctly with the latest version. Please note that the plugin has moved to NPM.
